### ISSUE TITLE
User section breaks when using laravel-translatable

### ISSUE THREAD

**Issue by adacnvwp** [spatie/ignition#44]
tasks_one:160 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%24%24typeof%2C%20type%2C%20key%2C%20ref%2C%20props%2C%20_owner%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at wo (tasks_one:160:62874)
    at tasks_one:160:67682
    at Gi (tasks_one:160:78640)
    at qi (tasks_one:160:80132)
    at Jl (tasks_one:160:123161)
    at wc (tasks_one:160:109704)
    at Cc (tasks_one:160:109632)
    at Lc (tasks_one:160:109495)
    at bc (tasks_one:160:106489)
    at tasks_one:160:56585
ml @ tasks_one:160
tasks_one:160 Uncaught Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%24%24typeof%2C%20type%2C%20key%2C%20ref%2C%20props%2C%20_owner%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at wo (tasks_one:160:62874)
    at tasks_one:160:67682
    at Gi (tasks_one:160:78640)
    at qi (tasks_one:160:80132)
    at Jl (tasks_one:160:123161)
    at wc (tasks_one:160:109704)
    at Cc (tasks_one:160:109632)
    at Lc (tasks_one:160:109495)
    at bc (tasks_one:160:106489)
    at tasks_one:160:56585
tasks_one#F46:1          Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by dawnbirth** [comment]
I was facing a similar issue, but after updating to version [1.1.0](https://github.com/spatie/ignition/releases/tag/1.1.0); the error page is no longer blank and the rendering error is now limited to the section that has the error.

For me, the error occurs in the "user" section as the user's "name" property is translated using "spatie laravel translatable" which converts it into an array instead of being a string by default and this causes a rendering error when trying to print the user name expecting it to be a text.

**Comment by AlexVanderbist** [comment]
Thanks for the detailed explanation! We'll tackle this soon 👍
