### ISSUE TITLE
93 errors inside DevTools console

### ISSUE THREAD

**Issue by iammati** [spatie/ignition#50]
Hi there, just tried out the package with a CMS (TYPO3) based on PHP which works like a charm - except a new exception I just ran into causes the following issue:

![image](https://user-images.githubusercontent.com/41418763/155601895-9c7dad48-aaf2-41fc-9751-cb3e2e45a9c3.png)

it doesn't spam my console only, but also JS (e.g. click) events are not working at all. Trying to collapse the vendor frames of the stacktrace but nothing happens.

I've shared the exception also here:
https://flareapp.io/share/17xjlVNm#share

BTW: I saw that `/_ignition/update-config` has a TODO comment, the README does not mention that at all, talking about non-laravel environment require a manual route handling for this to forward it to a specific controller/handler?

Thanks in advance,
Mati

**Comment by AlexVanderbist** [comment]
Hi @iammati! Thanks for trying out Ignition in a vanilla PHP app. 

We'll tag spatie/ignition 1.1.0 later today which will have:
- `vscode` as the default editor
- an `$ignition->setEditor()` method to specify your own editor
- a warning instead of an error when the editor is set to `null` or some unknown value

This will probably fix the issues your seeing right now 👍 

The `/_ignition/update-config` route is something that's used in laravel-ignition to be able to save the updated config values to a local file. Currently this is not yet supported in `spatie/ignition` but we plan on providing in depth documentation on how you can set up your own endpoint to do this later this year.

Thanks for reporting this issue!

**Comment by iammati** [comment]
The editor was for real causing the issue. It was `null` since the env-key wasn't present yet which lead to the errors.

Also thanks for the information about the route! :)
